spring:
  application:
    name: "afaja e-cash wallet integrator"

  r2dbc:
    url: ENC(RxFfj/EcGShd0JK8M3Hp3GddoEC2o4SXw65EmlJKHgMFdDH4HoTRxR/wWodjWfwazu8u+obMIP70BuEknP/Q3WVZDOEKgr9BDLi214JrILM=)
    username: ENC(1rsdN2jEHksVxRK7Ulq9qbyfERzThdkYy4jRLRkKvdbUT9Q+h4jXK2PHdvwMn93E)
    password: ENC(lM2MWKtxnxGLcl/YDOXKnOZGqoJTiUQZwgxwzY1piNxd9rjxfJ/XkQX9TzmkejxY)
    properties:
      schema: ENC(qMtS4Qja2E9JiSeGMI2QrrEN2R4Ryes3k9xtvNSt3YoQDjBnTJeg6eLgiCszy36Q)
    pool:
      enabled: true
      max-idle-time: 30m
      max-size: 40
      initial-size: 20

db-postgres:
  url: ENC(zQ48EpT/HRHgy/aZq8Q2WLLQ7w8qi2LRKZYLLIb9qaU/pfceZj34f5s7g/le/tR0ZqMJqjg4jCKHY5msPNv4/Ob/7h2op6qYsxdiRH3pAlEfQXNogW9QIUdIW0qyr4ci)
  username: ENC(8K2asB2iIlpLtKwkbmEJxYd43nAb7c4/sK+BHgkZ3OM6MPtlDK46EiZXoMo0VJs7)
  password: ENC(3HxSvAhngYaiOyd8085/XzO3OSTcYXSARjDSmSmeAa1ZV/PBfERL0k/ki5s2VnlY)
  schema: ENC(ZN/yLWoNKUJ0RGbwhAKHWNgybzsdH6TTc25+y1DkwgyU+kHk+9AHvcXX5q1nrlKB)

server:
  port: 9091

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
